### ISSUE TITLE
Requirements for HACS

### ISSUE THREAD

**Issue by klaasnicolaas** [peternijssen/lovelace-postnl-card#16]
Is it possible that you can adjust the repo to the [requirements](https://custom-components.github.io/hacs/#note-for-plugin-developers) that [HACS](https://github.com/custom-components/hacs) sets?

**Comment by peternijssen** [comment]
Yeah definitely. Was already going to take a look :)

**Comment by peternijssen** [comment]
Done!

https://community.home-assistant.io/t/lovelace-postnl/112433/111

**Comment by klaasnicolaas** [comment]
Nice!
