### ISSUE TITLE
International delivered shipment remains on the card

### ISSUE THREAD

**Issue by jrnhrmn** [peternijssen/lovelace-postnl-card#17]
I shipped something to France but the shipment still shows on the card. Status says Delivered but no delivery date. I can provide tracking data needed for testing.
Hopefully this can be solved.

**Comment by peternijssen** [comment]
@jrnhrmn Could you add a screenshot for starters? That perhaps helps me better understand. Thanks!

**Comment by jrnhrmn** [comment]
![Screenshot_20190603-003511~2__01](https://user-images.githubusercontent.com/50500175/58768236-54752f80-8598-11e9-9782-af665d6cf149.jpg)

**Comment by peternijssen** [comment]
Thanks for the screenshot. So unfortunately PostNL has no date of delivery so I cannot calculate if this package was recently delivered or ages ago. I am not sure yet what the correct solution is at this point.

**Comment by jrnhrmn** [comment]
Me neither. Parcel tracking continues at https://www.internationalparceltracking.com. Thanks for responding. I will find a way.
