### ISSUE TITLE
Error PostnlApi object has no attribute 'is_letters_activated'

### ISSUE THREAD

**Issue by jay448** [peternijssen/lovelace-postnl-card#18]
Tried to intergrate the component but i'm seeing the following error in the logging:
![image](https://user-images.githubusercontent.com/1663401/58947914-44707200-8789-11e9-81a1-95541bd2d53a.png)

It's stating that is_letters_activated has no attribute. Receiving letters is enabled in the app and i'm able to see the letters from the app. Because of this error it's not creating the sensor.postnl_letters
Therefore i'm only seeing these 2 views: 
![image](https://user-images.githubusercontent.com/1663401/58948059-944f3900-8789-11e9-9193-d70e5eb872e2.png)

**Comment by peternijssen** [comment]
I think your custom component is out of date.
https://gist.github.com/peternijssen/155c9060923adbc08d0998bbd8ed44bf

Please check both manifest.json and sensor.py have `postnlpy==0.4.1`. If not, make sure they have and restart HA.

**Comment by jay448** [comment]
Hi Peter,

You are right! I followed your post on the HA forums and copied the code shown in the link.
All is working properly now :) 

Thanks!
