### ISSUE TITLE
Strange letter titles?

### ISSUE THREAD

**Issue by schumi2004** [peternijssen/lovelace-postnl-card#23]
Is it normal to have strange titles for letters?
Can we give it some default text maybe so they are still clickable but doesn't look that strange?
![letters](https://user-images.githubusercontent.com/968545/69339676-2aa6e680-0c66-11ea-83ad-d7a2e1cae4a5.png)

**Comment by peternijssen** [comment]
These are the titles that PostNL assigns. Unfortunately they cannot be changed.

**Comment by schumi2004** [comment]
Okay, no problem. ;)
