### ISSUE TITLE
cant find the card in HACS

### ISSUE THREAD

**Issue by IIIdefconIII** [peternijssen/lovelace-postnl-card#26]
Hi, im not able to find the card in HACS

![afbeelding](https://user-images.githubusercontent.com/9917659/132832316-4d65e454-05f2-4ed4-8542-21ab3e643e26.png)

Is there any reason for this? im using latest homeassistant of today

**Comment by reharmsen** [comment]
This card, or actually the required components do not work anymore (for a long time).
PostNL does not allow API usage anymore.

**Comment by IIIdefconIII** [comment]
Ah to bad,  thanks for the response
